# Redes Neurais na pratica

In [3]:
#imports de libs
from sklearn import datasets
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix
from keras.models import Sequential
from keras.layers import Dense
from keras.utils import to_categorical
import numpy as np

In [5]:
# Carregamento da base de dados e criação dos provedores (variaveis independentes - x) e da classe (variavel dependente - y)
df = datasets.load_iris()
previsores = df.data
classe = df.target
classe

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [6]:
# Transformação da classe para o formato "dummy", pois temos uma rede neural com 3 neuronios na camada de saida
classe_dummy = to_categorical(classe)
classe_dummy

array([[1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0

In [7]:
# Divisão de dados entre treinamento e teste (30% para teste e 70% para treino)
x_train, x_test, y_train, y_test = train_test_split(previsores, classe_dummy, test_size=0.3,random_state=0)

In [8]:
# Criação da estrutura da rede neural com classe sequencial (sequencia de camadas)
modelo = Sequential()
# primeira camada oculta, 5 neuronios, 4 neuronios de entrada
modelo.add(Dense(units=5, input_dim=4))
# segunda camada oculta
modelo.add(Dense(units= 4))
# terceira camada oculta
# Função softmax, por conta de um problema de classificação com mais duas classes
#(é gerado uma probabilidade em cada neurônio)
modelo.add(Dense(units=3, activation='softmax'))

In [9]:
#Visualização da estrutura da rede neural
modelo.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 5)                 25        
                                                                 
 dense_1 (Dense)             (None, 4)                 24        
                                                                 
 dense_2 (Dense)             (None, 3)                 15        
                                                                 
Total params: 64 (256.00 Byte)
Trainable params: 64 (256.00 Byte)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [10]:
# Configuração dos parâmetros da rede neural (adam = algoritmo para atualizar os pesos e loss = cálculo de erro)
modelo.compile(optimizer= 'adam', loss= 'categorical_crossentropy', metrics=['accuracy'])
#Treinamento, dividindo a base de treinamento em uma porção para validação (validation_data)
modelo.fit(x_train, y_train, epochs=1000, validation_data= (x_test, y_test))


Epoch 1/1000


4/4 [==============================] - 1s 86ms/step - loss: 2.4862 - accuracy: 0.0000e+00 - val_loss: 2.7987 - val_accuracy: 0.0222
Epoch 2/1000
4/4 [==============================] - 0s 14ms/step - loss: 2.3534 - accuracy: 0.0095 - val_loss: 2.6653 - val_accuracy: 0.0667
Epoch 3/1000
4/4 [==============================] - 0s 13ms/step - loss: 2.2259 - accuracy: 0.1238 - val_loss: 2.5453 - val_accuracy: 0.1333
Epoch 4/1000
4/4 [==============================] - 0s 14ms/step - loss: 2.1318 - accuracy: 0.2286 - val_loss: 2.4352 - val_accuracy: 0.2000
Epoch 5/1000
4/4 [==============================] - 0s 13ms/step - loss: 2.0499 - accuracy: 0.3143 - val_loss: 2.3364 - val_accuracy: 0.2000
Epoch 6/1000
4/4 [==============================] - 0s 14ms/step - loss: 1.9653 - accuracy: 0.3429 - val_loss: 2.2530 - val_accuracy: 0.2222
Epoch 7/1000
4/4 [==============================] - 0s 14ms/step - loss: 1.9007 - accuracy: 0.3619 - val_loss: 2.1772 - val_accuracy: 0.2444
Epoch 

In [11]:
# previsões e mudar a variável para true ou false de acordo com o threshold 0.5
previsores = modelo.predict(x_test)
previsores = (previsores > 0.5)
previsores

2/2 [==============================] - 0s 3ms/step


array([[False, False,  True],
       [False,  True, False],
       [ True, False, False],
       [False, False,  True],
       [ True, False, False],
       [False, False,  True],
       [ True, False, False],
       [False,  True, False],
       [False,  True, False],
       [False,  True, False],
       [False, False,  True],
       [False,  True, False],
       [False,  True, False],
       [False,  True, False],
       [False,  True, False],
       [ True, False, False],
       [False,  True, False],
       [False,  True, False],
       [ True, False, False],
       [ True, False, False],
       [False, False,  True],
       [False,  True, False],
       [ True, False, False],
       [ True, False, False],
       [False, False,  True],
       [ True, False, False],
       [ True, False, False],
       [False,  True, False],
       [False,  True, False],
       [ True, False, False],
       [False, False,  True],
       [False,  True, False],
       [ True, False, False],
       [Fa

In [12]:
# Como é um problema com três saidas, precisamos buscar a posição que possui o maior valor (são retornado 3 valores)
y_test_matrix = [np.argmax(t) for t in y_test]
y_previsao_matrix = [np.argmax(t) for t in previsores]

In [13]:
# geração da matriz de confusão
confusao = confusion_matrix(y_test_matrix, y_previsao_matrix)
confusao

array([[16,  0,  0],
       [ 0, 17,  1],
       [ 0,  0, 11]], dtype=int64)